### ISSUE TITLE
Actividad 1. Práctica Prototipo de Escritorio

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-tec-design#2]
Integrantes de equipo:
González Lita Daisy  22620056
Santiago Bautista Maribel  22620262
[ReportePracticaMockup_TecDesign.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-tec-design/files/14168751/ReportePracticaMockup_TecDesign.pdf)

https://www.figma.com/file/TvMxsKxPFiNRzOYUVwbV8c/Untitled?type=design&node-id=0-1&mode=design&t=BGc0MtNQVwCGB8NW-0

**Comment by marxgonzalez29** [comment]
Tomando en cuenta los requisitos:
Tiene una buena presentación el proyecto, al igual que las faltas ortográficas son nulas también el proyecto es entendible...
La puntuación sería del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
